# Generated by Django 5.0.7 on 2024-08-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedback',
            name='image',
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
