# Generated by Django 5.0.7 on 2024-08-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_clientfeedback_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='image',
            new_name='image_base64',
        ),
    ]
