# Generated by Django 5.0.7 on 2024-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_teammember_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
