# Generated by Django 5.0.7 on 2024-07-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_clientfeedback_pricingplan_service_skillcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.JSONField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
